version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../datasets:/app/datasets
      - ../saved_models:/app/saved_models
      - ../exoplanets.db:/app/exoplanets.db
    environment:
      - ENV=production

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
